name: CI and CD for development environment deploy to cloudlet
on:
  push:
    branches: [ master ]
jobs:
  archive-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Remove files  
        run: rm -rf .git && rm -rf .github && rm -rf .vscode && rm -rf .gitignore
      - name: Replace Purchase URL
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "http://localhost:5000"
          replace: "https://schwoogle.servergardens.com"
          regex: false
      - name: Archive
        if: success()
        uses: vimtor/action-zip@v1
        with:
          files: ./
          dest: archive.zip
      - name: Deploy
        if: success()
        uses: fjogeleit/http-request-action@v1.14.0
        with:
          url: 'https://schwoogle.servergardens.com/magic/system/file-system/overwrite-folder'
          method: 'PUT'
          timeout: 50000
          customHeaders: '{
            "Content-Type": "multipart/form-data",
            "Authorization": "Bearer ${{ secrets.TOKEN }}"
            }'
          data: '{"folder": "/etc/www/"}'
          files: '{"file": "/home/runner/work/schwoogle/schwoogle/archive.zip"}'